### PR TITLE
Added mockingcase.log function

### PR DESCRIPTION
**Pull request by everspy**
I attempted to add the log function mentioned in issue #7. I'm not sure if the format is as desired, I am not used to NodeJS formatting.

### CODE REVIEW

**Comment by strdr4605** [comment]
@everspy Thank you, I will look in the near future!

**Comment by strdr4605** [comment]
I found the solution for `index.d.ts`

```ts
declare module 'mockingcase' {
  export = mockingcase;
  function mockingcase(input: string, options?: { random?: boolean }): string;
  namespace mockingcase {
    export function log(input: string, options?: { random?: boolean }): void;
  }
}
```

**Comment by strdr4605** [comment]
@everspy, would you like to also modify `index.d.ts`?

**Comment by everspy** [comment]
Thanks @strdr4605. I updated the `index.d.ts` file with the code you provided.

**Pull request merged**
